---
  - name: format disk
    filesystem:
        dev: '{{item.disk}}'
        fstype: ext4
    with_items:
        "{{dev_dict}}"
  - name: mkdir mount dir
    file:
        path: '{{item.dir}}'
        mode: 755
        state: directory
    with_items:
        "{{dev_dict}}"

  - name: mount disk
    mount:
        backup: yes
        opts: rw,noatime,nodiratime
        path: '{{item.dir}}'
        src: '{{item.disk}}'
        state: mounted
    with_items:
        "{{dev_dict}}"
